### ISSUE TITLE
Incorrect exceptions

### ISSUE THREAD

**Issue by dmitriitux** [polytope-jp/mod_poly_instagallery#1]
Hi,
If your results did not come from Facebook, an exception is thrown. And the data may not come for various reasons, it is an external service that may fall or may not be available, or the api has changed. And it turns out that ALL pages where this module is running will fall into error. Therefore, you need to remove the exceptions and just write some dummies or stubs in the log.

**Comment by polytope-jp** [comment]
Thank you for your feedback !
