### ISSUE TITLE
Loading delay

### ISSUE THREAD

**Issue by dmitriitux** [polytope-jp/mod_poly_instagallery#2]
if there is no cache, then you are receiving a response from Facebook during the assembly of the entire page. Since this is an external service, it may not be available and therefore the assembly of the page may be delayed or even fall. 

Therefore, it is necessary to transfer the loading of the module to Ajax so that it is in the background and does not interfere with the work, and if there is a cache, then you can display it already when building the page.

**Comment by polytope-jp** [comment]
Thank you for your feedback !
I've fixed this issue with version 1.2.1.
