### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by dmitriitux** [polytope-jp/mod_poly_instagallery#3]
according to the canons of jumla, all the statics must be moved to the "media" folder
create folder "media" and move the css, js, images folders there.
then, in xml file:

	<media folder="media" destination="mod_poly_instagallery">
		<folder>css</folder>
		<folder>images</folder>
		<folder>js</folder>
	</media>

**Comment by polytope-jp** [comment]
Thank you for your feedback !
