### ISSUE TITLE
No gallery

### ISSUE THREAD

**Issue by PowerAmbroz** [polytope-jp/mod_poly_instagallery#4]
Hi. I've did everything you said in the read me. Got the ID and the Access Token but no gallery is showing on my site.
Do you need tthe facebook account to be the same as the instagram account? Or could they be diffrent accounts?

Thanks for the help.

**Comment by polytope-jp** [comment]
Thank you for your inquiry.
Can you try to check your access token with the facebook tools (Access Token Debugger).

https://developers.facebook.com/tools/

![token](https://user-images.githubusercontent.com/28630230/110123526-579fee00-7e04-11eb-83ce-0e6a1301354b.png)

Check "Expires" and "Scopes".

Also check the error log.
{Joomla_root}/administrator/logs/mod_poly_instagallery.php
